### ISSUE TITLE
Create Landing Page 

### ISSUE THREAD

**Issue by Shari-alt** [Shari-alt/capstone-soulstop#1]
## Value Statement 

As a user of "HelpYourSoul" 
I want to be able to have an overview of the app 
so I know what is going on and get a feeling for it. 

## Description 

<img width="169" alt="Bildschirmfoto 2021-04-26 um 12 03 23" src="https://user-images.githubusercontent.com/70467197/116065539-6928a800-a687-11eb-89ba-152584361cac.png">

## Acceptance Criteria

- On the landing page the user should have two buttons to get an overview 
- the user should have a comfortable feeling 

## Tasks

- [x] Add the background picture for the whole app 
- [x] create a new component for the `landing page`
- [x] create two buttons 

## Complexity 

Small
