### ISSUE TITLE
Create the single view of an clinic

### ISSUE THREAD

**Issue by Shari-alt** [Shari-alt/capstone-soulstop#11]
## Value Statement 

As a user 
I want to have a look on every clinic
so I can see the detailed information. 

## Description

![image](https://user-images.githubusercontent.com/70467197/116564964-b7e37580-a905-11eb-9b26-8c796b83014b.png)

## Acceptance Critera

- create a new page
- have an ShowSingleClinic-Card Component 
- styled with CSS

## Tasks

- [ ] create a new page
- [ ] create a ShowSingleClinic-Card Component 
- [ ] create useHistory to get back
- [ ] create button to directly edit it
