### ISSUE TITLE
Create the Edit Card

### ISSUE THREAD

**Issue by Shari-alt** [Shari-alt/capstone-soulstop#12]
## Value Statement 

As a user 
I want to change the given information of the clinics
so I can always keep them updated or add things. 

## Description

![image](https://user-images.githubusercontent.com/70467197/116566151-cc743d80-a906-11eb-9da0-d12042bb1eab.png)

## Acceptance Critera

- create a new page
- have the Input Formular 
- added the Buttons
- styled with CSS

## Tasks

- [x] create a new page
- [x] create an Input Formular
- [x] create useHistory to get back
- [x] create button to directly edit it
