### ISSUE TITLE
Implement Local Storage 

### ISSUE THREAD

**Issue by Shari-alt** [Shari-alt/capstone-soulstop#14]
## Value Statement 

As a user 
I want to be able to add a clinic
and have it stored in my local storage.

## Acceptance Critera

- add a clinic to the local storage 
- be able to see it on the list page  
- add it to your favourites
- be able to edit the clinic
- and delete the clinic 

## Tasks

- [] implement local storage
- [] add a clinic
- [] see it on the list page 
- [] delete the clinic
- [] edit the clinic
- []safe the clinic in favourites
