### ISSUE TITLE
Create App setup

### ISSUE THREAD

**Issue by Shari-alt** [Shari-alt/capstone-soulstop#2]
## Description

- setup the App.js 

## Acceptance Critera

- the basic grid is working 
- create a component for the footer inkl. the navigation bar 

## Tasks

- [x] create a grid in app.css
- [x] import icons from favicon 
- [x] create a component folder
- [x] create a component for the footer with the navigation
- [x] add the background picture
