### ISSUE TITLE
Create components for the buttons

### ISSUE THREAD

**Issue by Shari-alt** [Shari-alt/capstone-soulstop#3]
## Value statement
As a user I should directly recognize the button 
so they need to look the same. 

## Description 

<img width="171" alt="Bildschirmfoto 2021-04-26 um 11 59 55" src="https://user-images.githubusercontent.com/70467197/116065079-ec95c980-a686-11eb-9591-5e3590d6f6ca.png">

## Acceptance Criteria
- the user should directly see where to press 
- so the user should be able to add a clinic, see the list or go directly to the guide 

## Tasks
- [x] Add button with the same color 
- [x] add the font 
- [x] create it with a shadow
