### ISSUE TITLE
Create an empty ClinicCard Component

### ISSUE THREAD

**Issue by Shari-alt** [Shari-alt/capstone-soulstop#6]
##Value Statement 

As a user 
I want to be able to see the Clinics shown in Cards as a list
so I have an overview of my added clinics and scroll through them.

## Description

![Bildschirmfoto 2021-04-28 um 15 46 25](https://user-images.githubusercontent.com/70467197/116414624-e6dfe580-a838-11eb-8fbf-a313b0098069.png)

## Acceptance Critera

- the card is formated 
- card is styled 
- has placeholder as a text and image 
- add an edit and safe button 

## Tasks

- [x] create a component
- [x] import icons as svg
- [x] create an example card
- [x] make it scrollable
