### ISSUE TITLE
Create the Checklist 

### ISSUE THREAD

**Issue by Shari-alt** [Shari-alt/capstone-soulstop#9]
## Value Statement 

As a user 
I want to organize my tasks 
so it's easier to keep them in mind. 

## Description

![image](https://user-images.githubusercontent.com/70467197/116563828-b06f9c80-a904-11eb-9c6e-c95e02dba0ea.png)

## Acceptance Critera

- create a checklist Page
- have an To-Do-Card Component 
- having an formated alert 

## Tasks

- [x] create a new page
- [x] create a To-Do-Card Component 
- [x] create the Add Button with an Alert
- [x] Style the Alert with Adding new To-Do's
